% readcomcat - Read CSV files as generated by ComCat search API.
%   data = readsmgrid(csvfile);
%   Input:
%    - csvfile is a valid filename for a ComCat CSV file.
%   Output:
%    - data is a Matlab structure array, with each element containing fields:
%      - time Matlab datenum of origin time.
%      - lat  Latitude of origin.
%      - lon  Longitude of origin.
%      - depth Depth of origin.
%      - mag   Magnitude of origin.
%      - magtype Magnitude type (Mb, Ms, etc.)
%      - nst     Number of stations used to determine the solution.
%      - dmin    ??
%      - rms     Root mean square error of ??
%      - net     Contributing network of origin.
%      - id      Event id
%      - updated Matlab datenum Time of most recent origin update.
%      - place   String indicating location of epicenter.
%      - type    Usually earthquake, but may be mine collapse, mining explosion, etc.
function [data] = readcomcat(csvfile)
    TIMEFMT = 'yyyy-mm-ddTHH:MM:SS.FFF';
    data = struct([]);
    fid = fopen(csvfile);
    tline = fgetl(fid);
    tline = fgetl(fid);
    i = 1;
    while (ischar(tline))
        try
            parts = regexpi(tline,',','split');
        catch
            x = 1;
        end
        timestr = parts{1}(1:23);
        data(i).time = datenum(timestr,TIMEFMT);
        data(i).lat = str2double(parts{2});
        data(i).lon = str2double(parts{3});
        data(i).depth = str2double(parts{4});
        data(i).mag = str2double(parts{5});
        data(i).magtype = parts{6};
        data(i).nst = str2num(parts{7});
        data(i).gap = str2double(parts{8});
        data(i).dmin = str2double(parts{9});
        data(i).rms = str2double(parts{10});
        data(i).net = parts{11};
        data(i).id = parts{12};
        data(i).updated = datenum(parts{13}(1:23),TIMEFMT);
        data(i).place = parts{14};
        data(i).type = parts{15};
        data(i) = data(i);
        i = i + 1;
        tline = fgetl(fid);
    end
    fclose(fid);
    
end